# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SwiftUI-CameraApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SwiftUI-CameraApp
    pod 'JPSVolumeButtonHandler'

  target 'SwiftUI-CameraAppTests' do
    inherit! :search_paths
    # Pods for testing
     pod 'JPSVolumeButtonHandler'
  end

  target 'SwiftUI-CameraAppUITests' do
    # Pods for testing
     pod 'JPSVolumeButtonHandler'
  end

end
